// Generated by com.nm.GridEditGenerator at Tue Sep 01 08:40:03 EEST 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import com.xgraf.RecordEditPanel;
import com.xgraf.orm.dbobject.DbObject;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

public class EditContactPanel extends RecordEditPanel {
 
    public EditContactPanel(DbObject dbObject) {
        super(dbObject);
    }

//column: contact_id type: INT class: java.lang.Integer
    private JTextField contactIdField;
//column: name type: VARCHAR class: java.lang.String
    private JTextField nameField;
//column: phone type: VARCHAR class: java.lang.String
    private JTextField phoneField;
//column: email type: VARCHAR class: java.lang.String
    private JTextField emailField;
//column: email1 type: VARCHAR class: java.lang.String
    private JTextField email1Field;
//column: comments type: VARCHAR class: java.lang.String
    private JTextField commentsField;

    @Override
    protected void fillContent() {
        //TODO
    }

    @Override
    public void loadData() {
        //TODO
    }

    @Override
    public boolean save() throws Exception {
        //TODO
        return true;
    }
}

