// Generated by com.nm.GridEditGenerator at Mon Aug 31 18:35:20 EEST 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import com.xgraf.RecordEditPanel;
import com.xgraf.orm.dbobject.DbObject;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

public class EditCompanyPanel extends RecordEditPanel {

//column: company_id type: INT class: java.lang.Integer
    private JTextField companyIdField;
//column: name type: VARCHAR class: java.lang.String
    private JTextField nameField;
//column: street type: VARCHAR class: java.lang.String
    private JTextField streetField;
//column: area_pobox type: VARCHAR class: java.lang.String
    private JTextField areaPoboxField;
//column: city type: VARCHAR class: java.lang.String
    private JTextField cityField;
//column: postcode type: VARCHAR class: java.lang.String
    private JTextField postcodeField;
//column: reg_no type: VARCHAR class: java.lang.String
    private JTextField regNoField;
//column: vat_no type: VARCHAR class: java.lang.String
    private JTextField vatNoField;
//column: comments type: VARCHAR class: java.lang.String
    private JTextField commentsField;

    public EditCompanyPanel(DbObject dbObject) {
        super(dbObject);
    }

    @Override
    protected void fillContent() {
        //TODO
    }

    @Override
    public void loadData() {
        //TODO
    }

    @Override
    public boolean save() throws Exception {
        //TODO
        return true;
    }
}
