// Generated by com.nm.GridEditGenerator at Mon Aug 31 18:35:20 EEST 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import com.xgraf.EditRecordDialog;
import com.xgraf.orm.Company;

public class EditCompanyDialog extends EditRecordDialog {

    public static boolean okPressed;
    public EditCompanyDialog(String title, Company rec) {
        super(title, rec);
    }

    @Override
    protected void fillContent() {
        super.fillContent(new EditCompanyPanel((Company) getObject()));
    }

    @Override
    protected void setOkPressed(boolean b) {
        okPressed = b;
    }
}

