// Generated by com.nm.GridEditGenerator at Thu Oct 29 08:45:37 EET 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import static com.xgraf.RecordEditPanel.getBorderPanel;
import static com.xgraf.RecordEditPanel.getGridPanel;
import com.xgraf.orm.dbobject.DbObject;
import com.xlend.util.Java2sAutoComboBox;
import com.xlend.util.SelectedDateSpinner;
import com.xlend.util.SelectedNumberSpinner;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class EditStatementPanel extends RecordEditPanel {
    private SelectedDateSpinner statementDateSP;
    private JLabel dtlLbl;
    private JLabel termsLbl;
  

    public EditStatementPanel(DbObject dbObject) {
        super(dbObject);
    }

//column: statement_id type: INT class: java.lang.Integer
    private JTextField idField;
//column: company_id type: INT class: java.lang.Integer
    private JComboBox companyIdComboBox;
//column: contact_id type: INT class: java.lang.Integer
    private JComboBox contactIdComboBox;
//column: statement_ref type: VARCHAR class: java.lang.String
    private JTextField statementRefField;
//column: statement_date type: DATE class: java.sql.Date
//column: outstanding_balance type: DECIMAL class: java.math.BigDecimal
//column: bank_acc_holder type: VARCHAR class: java.lang.String
    private JTextField bankAccHolderField;
//column: bank type: VARCHAR class: java.lang.String
    private JTextField bankField;
//column: bank_branch_code type: VARCHAR class: java.lang.String
    private JTextField bankBranchCodeField;
//column: bank_acc_no type: VARCHAR class: java.lang.String
    private JTextField bankAccNoField;
//column: bank_acc_type type: VARCHAR class: java.lang.String
    private Java2sAutoComboBox bankAccTypeCB;
//column: payment_due type: TINYINT class: java.lang.Integer
    private SelectedNumberSpinner paymentDueNumberSpinner;

    @Override
    protected void fillContent() {
        String[] titles = {
            "ID:",
            "Statement ref #:",
            "Date:",
            "<html><b>Banking </b></html>",
            "Acc holder:",
            "Bank:",
            "Branch Code:",
            "Account No:",
            "Account Type:",
            "<html><b>Terms & </b></html>",
        };
        JComponent[] edits = new JComponent[]{
            getGridPanel(idField = new JTextField(), 5),
            getGridPanel(statementRefField = new JTextField(12), 2),
            getBorderPanel(new JComponent[]{
                statementDateSP = new SelectedDateSpinner(),
                new JPanel(), new JPanel()
            }),
            dtlLbl = new JLabel("Details"),
            bankAccHolderField = new JTextField(),
            bankField = new JTextField(),
            getGridPanel(bankBranchCodeField = new JTextField(), 3),
            getGridPanel(bankAccNoField = new JTextField(), 3),
            bankAccTypeCB = new Java2sAutoComboBox(XGrafWorks.loadDistinct("statement", "bank_acc_type")),
            termsLbl = new JLabel("Conditions"),
        };
        
        organizePanels(titles, edits, null);
        //TODO
    }

    @Override
    public void loadData() {
        //TODO
    }

    @Override
    public boolean save() throws Exception {
        //TODO
        return true;
    }
}
