// Generated by com.nm.GridEditGenerator at Sun Sep 13 09:56:58 EEST 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import com.xgraf.EditRecordDialog;
import com.xgraf.orm.Quote;

public class EditQuoteDialog extends EditRecordDialog {

    public static boolean okPressed;
    public EditQuoteDialog(String title, Quote rec) {
        super(title, rec);
    }

    @Override
    protected void fillContent() {
        super.fillContent(new EditQuotePanel((Quote) getObject()));
    }

    @Override
    protected void setOkPressed(boolean b) {
        okPressed = b;
    }
}

