// Generated by com.nm.GridEditGenerator at Thu Oct 29 08:45:37 EET 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import com.xgraf.orm.Statement;
import javax.swing.JButton;
import javax.swing.JPanel;

public class EditStatementDialog extends EditRecordDialog {

    public static boolean okPressed;
    public EditStatementDialog(String title, Statement rec) {
        super(title, rec);
    }

    @Override
    protected void fillContent() {
        super.fillContent(new EditStatementPanel((Statement) getObject()));
    }

    @Override
    protected void setOkPressed(boolean b) {
        okPressed = b;
    }
    
    @Override
    protected void addBeforeButtons(JPanel btnPanel) {  
        btnPanel.add(new JButton(((EditStatementPanel)getEditPanel()).printAction()));
    }
}

