// Generated by com.nm.GridEditGenerator at Sun Sep 13 09:56:58 EEST 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import com.xgraf.RecordEditPanel;
import com.xgraf.orm.dbobject.DbObject;
import com.xlend.util.SelectedNumberSpinner;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;

public class EditQuotePanel extends RecordEditPanel {

public EditQuotePanel(DbObject dbObject) {
        super(dbObject);
    }

//column: quote_id type: INT class: java.lang.Integer
    private JTextField quoteIdField;
//column: company_id type: INT class: java.lang.Integer
    private JComboBox companyIdComboBox;
//column: contact_id type: INT class: java.lang.Integer
    private JComboBox contactIdComboBox;
//column: quote_ref type: VARCHAR class: java.lang.String
    private JTextField quoteRefField;
//column: order_no type: VARCHAR class: java.lang.String
    private JTextField orderNoField;
//column: quote_date type: DATE class: java.sql.Date
//column: is_proforma type: BIT class: java.lang.Boolean
    private JCheckBox isProformaCheckBox;
//column: sub_total type: DECIMAL class: java.math.BigDecimal
//column: bank_acc_holder type: VARCHAR class: java.lang.String
    private JTextField bankAccHolderField;
//column: bank type: VARCHAR class: java.lang.String
    private JTextField bankField;
//column: bank_branch_code type: VARCHAR class: java.lang.String
    private JTextField bankBranchCodeField;
//column: bank_acc_no type: VARCHAR class: java.lang.String
    private JTextField bankAccNoField;
//column: bank_acc_type type: VARCHAR class: java.lang.String
    private JTextField bankAccTypeField;
//column: valid_term type: DATE class: java.sql.Date
//column: deposit_percent type: DECIMAL class: java.math.BigDecimal
//column: refund_break_percent type: DECIMAL class: java.math.BigDecimal
//column: outbalance_weeks type: TINYINT class: java.lang.Integer
    private SelectedNumberSpinner outbalanceWeeksNumberSpinner;
//column: pref_pay_method type: VARCHAR class: java.lang.String
    private JTextField prefPayMethodField;
//column: add_conditions type: VARCHAR class: java.lang.String
    private JTextField addConditionsField;

    @Override
    protected void fillContent() {
        //TODO
    }

    @Override
    public void loadData() {
        //TODO
    }

    @Override
    public boolean save() throws Exception {
        //TODO
        return true;
    }
}

