// Generated by com.nm.GridEditGenerator at Fri Oct 30 16:44:52 EET 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import com.xgraf.orm.dbobject.DbObject;
import javax.swing.JComboBox;
import javax.swing.JTextField;

public class EditStatementitemPanel extends RecordEditPanel {

    public EditStatementitemPanel(DbObject dbObject) {
        super(dbObject);
    }

//column: statementitem_id type: INT class: java.lang.Integer
    private JTextField statementitemIdField;
//column: statement_id type: INT class: java.lang.Integer
    private JComboBox statementIdComboBox;
//column: stitem_date type: DATE class: java.sql.Date
//column: stitem_ref type: VARCHAR class: java.lang.String
    private JTextField stitemRefField;
//column: descry type: VARCHAR class: java.lang.String
    private JTextField descryField;
//column: amount type: DECIMAL class: java.math.BigDecimal
//column: payment type: DECIMAL class: java.math.BigDecimal
//column: balance type: DECIMAL class: java.math.BigDecimal

    @Override
    protected void fillContent() {
        //TODO
    }

    @Override
    public void loadData() {
        //TODO
    }

    @Override
    public boolean save() throws Exception {
        //TODO
        return true;
    }
}
