// Generated by com.nm.GridEditGenerator at Sun Sep 13 09:56:58 EEST 2015
// generated file, so all hand editions will be overwritten
package com.xgraf;

import com.xgraf.orm.IDocument;
import com.xgraf.orm.Quote;
import javax.swing.JButton;
import javax.swing.JPanel;

public class EditQuoteDialog extends EditRecordDialog {

    public static boolean okPressed;
    public EditQuoteDialog(String title, IDocument rec) {
        super(title, rec);
    }

    @Override
    protected void fillContent() {
        super.fillContent(new EditQuotePanel((Quote) getObject()));
    }

    @Override
    protected void setOkPressed(boolean b) {
        okPressed = b;
    }
    
    @Override
    protected void addBeforeButtons(JPanel btnPanel) {  
        btnPanel.add(new JButton(((EditQuotePanel)getEditPanel()).printAction()));
    }
}

